export const products = [
    {
      name: "medicare",
      label: "Medicare",
      toggleSwitch1: "medicareSMS",
      toggleSwitch2: "medicareEmail",
      toggleSwitch3: "medicareWhatsapp",
      startDate: "medicareStartDate",
      endDate: "medicareEndDate",
      startTime: "medicareStartTime",
      endTime: "medicareEndTime",
    },
    {
      name: "medicarePremier",
      label: "Medicare Premier",
      toggleSwitch1: "medicarePremierSMS",
      toggleSwitch2: "medicarePremierEmail",
      toggleSwitch3: "medicarePremierWhatsapp",
      startDate: "medicarePremierStartDate",
      endDate: "medicarePremierEndDate",
      startTime: "medicarePremierStartTime",
      endTime: "medicarePremierEndTime",
    },
    {
      name: "medicarePremierRevised",
      label: "Medicare Premier Revised",
      toggleSwitch1: "medicarePremierRevisedSMS",
      toggleSwitch2: "medicarePremierRevisedEmail",
      toggleSwitch3: "medicarePremierRevisedWhatsapp",
      startDate: "medicarePremierRevisedStartDate",
      endDate: "medicarePremierRevisedEndDate",
      startTime: "medicarePremierRevisedStartTime",
      endTime: "medicarePremierRevisedEndTime",
    },
    {
      name: "medicareProtect",
      label: "Medicare Protect",
      toggleSwitch1: "medicareProtectSMS",
      toggleSwitch2: "medicareProtectEmail",
      toggleSwitch3: "medicareProtectWhatsapp",
      startDate: "medicareProtectStartDate",
      endDate: "medicareProtectEndDate",
      startTime: "medicareProtectStartTime",
      endTime: "medicareProtectEndTime",
    },
    {
      name: "medicareRevised",
      label: "Medicare Revised",
      toggleSwitch1: "medicareRevisedSMS",
      toggleSwitch2: "medicareRevisedEmail",
      toggleSwitch3: "medicareRevisedWhatsapp",
      startDate: "medicareRevisedStartDate",
      endDate: "medicareRevisedEndDate",
      startTime: "medicareRevisedStartTime",
      endTime: "medicareRevisedEndTime",
    },
    {
      name: "medicarePlus",
      label: "Medicare Plus",
      toggleSwitch1: "medicarePlusSMS",
      toggleSwitch2: "medicarePlusEmail",
      toggleSwitch3: "medicarePlusWhatsapp",
      startDate: "medicarePlusStartDate",
      endDate: "medicarePlusEndDate",
      startTime: "medicarePlusStartTime",
      endTime: "medicarePlusEndTime",
    },
    {
      name: "critiMedicare",
      label: "Criti-Medicare",
      toggleSwitch1: "critiMedicareSMS",
      toggleSwitch2: "critiMedicareEmail",
      toggleSwitch3: "critiMedicareWhatsapp",
      startDate: "critiMedicareStartDate",
      endDate: "critiMedicareEndDate",
      startTime: "critiMedicareStartTime",
      endTime: "critiMedicareEndTime",
    },
  ];