const apiUrls = {
  postLogin: '/api/login',
  fetchUserCreationJSON: '/userCreationData.json',
  getLoginType: '/api/login-type',
  getUserType: '/api/user-type',
  postUserCreation: '/api/user',
  getRoleHierarchy: '/api/role-hierarchy',
  getChannelType: '/api/channel',
  getHouseBank: '/api/house-bank',
  getLob: '/api/lob',
  getLocation: '/api/location',
  getParentCode: '/api/role',
  getPaymentType: '/api/payment-type',
  getUser: '/api/user',
  getProduct: '/api/product',
  getRole: '/api/role',
  getPermission: '/api/permission',
  module: '/api/module',
  channel: '/api/channel',
  ckyc: '/api/ckyc',
  employeeFlag: 'api/employee-flag-config',
  healthConfig: 'api/health-configuration',
  paymentProduct: 'api/product-wise-payment-method',
  productLocationLevelMapping: 'api/product-location-level-mapping',
  getGroup: '/api/group',
  getProducerType: '/api/producer-type',
  houseBank: '/api/house-bank',
  getEodByPass: '/api/producer-eod-bypass',
  getOTPException: '/api/otp-exception',
  role: '/api/role',
  getBulkUploadHistory:'/api/file/upload-history',
  postBulkUpload: '/api/file/bulk-upload',
  downloadBulkTemplate: '/api/file/download-sample-file',
  proposalOtpException: "/api/proposal-otp-exception",
  proposalBitlyConfig: "/api/proposal-bitly-config",
  getColumns: "/api/file/columns?tableName=",
  downloadFile: "/api/file/download",
  getZone: "/api/zone",
  getPlan: '/api/plan',
  getMasterPolicy: "/api/master-policy",
};

export default apiUrls;
