const apiUrls = {
  postLogin: '/api/login',
  fetchUserCreationJSON: '/userCreationData.json',
  getLoginType: '/api/login-type',
  getUserType: '/api/user-type',
  postUserCreation: '/api/user',
  getRoleHierarchy: '/api/role-hierarchy',
  getChannelType: '/api/channel',
  getHouseBank: '/api/house-bank',
  getLob: '/api/lob',
  getLocation: '/api/location',
  getParentCode: '/api/role',
  getPaymentType: '/api/payment-type',
  getUser: '/api/user',
  getProduct: '/api/product',
  getRole: '/api/role',
  getPermission: '/api/permission',
  module: '/api/module',
  channel: '/api/channel',
  ckyc: '/api/ckyc',
  employeeFlag: 'api/employee-flag-config',
  healthConfig: 'api/health-configuration',
  paymentProduct: 'api/product-wise-payment-method',
  productLocationLevelMapping: 'api/product-location-level-mapping',
};

export default apiUrls;
