export const COMMON_WORDS = {
  PRODUCER: 'producer',
  USER_TYPE: 'userType',
  ROLE_NAME: 'roleName',
  PRODUCT: 'product',
  ASC: 'asc',
  LOB: 'lob',
  CREATED_AT: 'createdAt',
  ENABLE: 'Enable',
  DISABLE: 'Disable',
  CHANGE_STATUS: 'Change Status',
  LOGOUT: 'Logout',
  HAS_PRODUCER: 'hasProducer',
  HAS_PRODUCT: 'hasProduct',
  HAS_LOB: 'hasLob',
  SELECT: 'Select',
  USER: 'user',
  PRODUCTS: 'products',
  LOBS: 'lobs',
  HAS_PAYMENT_TYPE: 'hasPaymentType',
  PAYMENTS: 'payments',
  LOCATIONS: 'locations',
  HAS_LOCATION: 'hasLocation',
  UNDERWRITER: 'underWriter',
  PERMISSION: 'permission',
  PERMISSIONNAME: 'permissionName',
  GROUP: 'group',
  SEARCH: 'search',
  STATUS: 'status',
};

export const HEADER = {
  DRAWER_WIDTH: 240,
};

export const CHANGE_STATUS_LABEL = {
  UNDERWRITER_LEVEL: 'Underwriter Level Mapping',
};

export const FORM_HEADER_TEXT = {
  COMMUNICATION_RESTRICTION: 'Communication Restriction',
  PARTNER_NEFT_FLAG: 'Partner NEFT Flag',
  BANCA_FIELDS: 'Banca Fields',
  CKYC_CONFIG: 'CKYC Config',
  EMPLOYEE_FLAG: 'Employee Flag Configuration',
  GROUP: 'Group',
  HEALTH_CONFIG: 'Health Configuration',
  HOUSE_BANK: 'House Bank Configuration',
  LOB: 'Lob',
  OTP_EXCEPTION: 'Set OTP Exception By',
  PERMISSION: 'Permission',
  PRODUCER_EOD: 'Producer EOD Bypass',
  PRODUCT: 'Product',
  PAYMENT_CONFIG: 'Payment Configuration',
  CONFIG: 'Config',
  PROPOSAL_OTP: 'Proposal OTP Exception',
  ROLE: 'Role',
  USER: 'User',
  PRODUCT_LOCATION: 'Product Location Level',
};
