export const COMMON_WORDS = {
  PRODUCER: "producer",
  USER_TYPE: "userType",
  ROLE_NAME: "roleName",
  PRODUCT: "product",
  ASC: "asc",
  LOB: "lob",
  CREATED_AT: "createdAt",
  ENABLE: "Enable",
  DISABLE: "Disable",
  CHANGE_STATUS: "Change Status",
  LOGOUT: "Logout",
  HAS_PRODUCER: "hasProducer",
  HAS_PRODUCT: "hasProduct",
  HAS_LOB: "hasLob",
  SELECT: "Select",
  USER: "user",
  PRODUCTS: "products",
  LOBS: "lobs",
  HAS_PAYMENT_TYPE: "hasPaymentType",
  PAYMENTS: "payments",
  PERMISSION: "permission",
  PERMISSIONNAME: "permissionName",
};

export const HEADER = {
  DRAWER_WIDTH: 240,
  HEADER_BACKGROUND_COLOR: "#FFFFFF",
  ICON_COLOR: "#465465",
  TEXT_COLOR: "#465465",
  HEADING_FONT_WEIGHT: 600,
};
